---
- name: Install and start Apache
  hosts: webservers
  become: true

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
    - name: copy
      copy:
        soure: httpd
        dest: var/www/index.html
