---
- name: Install and start Apache
  hosts: webservers
  become: true

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
    - name: Start Apache server
      service:
        name: httpd
        state: started
    - name: copy
      copy:
        soure: index.html
        dest: /var/www/html/
